config/routes.rb
Rails.application.routes.draw do
  root to:'homes#top'
  get 'home/about' => 'homes#about'
  devise_for :users
  resources :users,only: [:show,:index,:edit,:update]
  resources :books
  get 'danger' => 'books#danger', as: "danger"
  get 'ougon' => 'users#ougon', as: "ougon"
  get 'correct' => 'users#correct', as: "correct"
  get 'dangerbtn' => 'users#dangerbtn', as: "dangerbtn"
  get "zoma" => "boss#zoma", as: "boss" 
  get "clear" => "boss#clear", as: "clear" 
  get "takarabako" => "boss#takarabako", as: "takarabako" 
  get "notice" => "books#notice", as: "notice"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
	belongs_to :user

	validates :title, presence: true
	validates :body, presence: true, length: {maximum: 200}
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable,:validatable

  attachment :profile_image, destroy: false
  has_many :books, dependent: :destroy

  validates :name, uniqueness: true
  validates :name, length: {maximum: 20, minimum: 2}
  validates :introduction, length: {maximum: 50}
end

#   devise :database_authenticatable, :registerable,
#          :recoverable, :rememberable, :trackable,:validatable
  
#   attachment :profile_image, destroy: false
#   has_many :books, dependent: :destroy

#   #バリデーションは該当するモデルに設定する。エラーにする条件を設定できる。
#   validates :name, length: {maximum: 20, minimum: 2}
#   validates :introduction, length: {maximum: 50}

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!,except: [:top, :about, :danger, :dangerbtn]
	before_action :configure_permitted_parameters, if: :devise_controller?
	protect_from_forgery with: :exception

  protected
  def after_sign_in_path_for(resource)
    if params[:user][:name] == "Nishikawa"
      ougon_path
    else
      user_path(resource)
    end
  end

  def after_sign_out_path_for(resource)
    root_path
  end

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email])
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :correct_user, only: [:edit]

  def show
    @book = Book.find(params[:id])
    @booknew = Book.new
    @user = @book.user

  end

  def index
    @book = Book.new
    @books = Book.all
  end

  def create
    @book = Book.new(book_params)
    if book_params[:title] == "冒険の書"
      @book.save
      redirect_to boss_path
    else
      @book.user_id = current_user.id
      if @book.save
        redirect_to book_path(@book), notice: "You have created book successfully."
      else
        @books = Book.all
        render :index
      end
    end
  end

  def edit
    if @book.user_id == current_user
      @book = Book.find(params[:id])
      render :edit
    else
        @book.user = current_user
        render :edit
    end
  end
  


  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      redirect_to book_path(@book), notice: "You have updated book successfully."
    else
      render "edit"
    end
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    redirect_to books_path, notice: "successfully delete book!"
  end

  def danger
    puts "ここは危険だ。"
  end

  def notice
  end


private

  def book_params
    params.require(:book).permit(:title, :body)
  end
  
  def correct_user
    @book = Book.find(params[:id])
    # redirect_to user_path(current_user.id) unless params[:id] == cur÷rent_user.id
    redirect_to(books_url) unless @book.user == current_user

  end
end

app/controllers/boss_controller.rb
class BossController < ApplicationController
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end

  def about
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :ensure_correct_user, only: [:edit]

  def show
    @user = User.find(params[:id])
    @books = @user.books
    @book = Book.new
  end

  def index
    @book = Book.new
    @users = User.all
    @user = current_user
  end

  def edit
    if @user == current_user
      @user = User.find(params[:id])
				render :edit
			else
        @user = current_user
        # render user_path(current_user.id)
        render :edit
      end
    end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to user_path(@user), notice: "You have updated user successfully."
    else
      render :edit
    end
  end

  def ougon
    puts "今日の酒は美味いか？"
    @sake = "優勝"

    if @sake == "優勝"
      puts "二次会、行くよね？"
    end
  end

  def correct
    @point = 10
    @test = "と、見せかけて…？"
  end

  def dangerbtn
    @point = 3
  end

  private
  def user_params
    params.require(:user).permit(:name, :introduction, :profile_image)
  end

  def ensure_correct_user
    @user = User.find(params[:id])
    unless @user == current_user
      redirect_to user_path(current_user)
   end   
  end
  end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/boss_helper.rb
module BossHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_form.html.erb
<%= form_with model:book,local:true do |f| %>
  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, class: 'form-control book_title' %>
  </div>
  <div class="form-group">
    <%= f.label :opinion %>
    <%= f.text_area :body, class: 'form-control book_body' %>
  </div>
  <div class="form-group">
    <%= f.submit class: 'btn btn-success' %>
  </div>
<% end %>

app/views/books/_index.html.erb
<table class='table table-hover table-inverse'>
  <thead>
    <tr>
      <th></th>
      <th>Title</th>
      <th>Opinion</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% books.each do |book| %>
      <tr>
        <td>
        <%= link_to user_path(book.user) do %>
				<%= attachment_image_tag(book.user, :profile_image, :fill, 50, 50, fallback: "no-image-mini.jpg") %>
        <% end %>
        </td>
        <td><%= link_to book.title, book_path(book), class: "book_#{book.id}" %></td>
        <td><%= book.body %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/books/danger.html.erb
<div class='container px-5 px-sm-0'>
  <div class='row'>
    <div class='col-md-6'>
      <h2>ここには何もないようだ。</h2>
      <h2>あなたは0点を獲得した。</h2>
    </div>
  </div>
</div>

app/views/books/edit.html.erb
<div class='container'>
  <div class='row'>
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
  		<h1>Editing Book</h1>
    	<%= render 'layouts/errors', obj: @book %>
  		<%= render 'form', book: @book %>
  		<%= link_to 'Show', book_path(@book), class: "book_#{@book.id}" %> |
  		<%= link_to 'Back', books_path, class: "back" %>|
  		<%= link_to '宝箱', takarabako_path %>|
  </div>
</div>

app/views/books/index.html.erb
<div class='container px-5 px-sm-0'>
  <div class='row'>
    <div class='col-md-3'>
      <h2>User info</h2>
      <%= render 'layouts/errors', obj: @book %>

      <%= render 'users/info', user: current_user %>
      <h2 class="mt-3">New book</h2>
      <%= render 'form', book: @book %>
    </div>
    <div class='col-md-8 offset-md-1'>
      <h2>Books</h2>
      <%= render 'index', books: @books %>
    </div>
  </div>
</div>

app/views/books/notice.html.erb
<div class='container px-5 px-sm-0'>
  <div class='row'>
    <div class='col-md-10'>
      <h1>クイズ：正解したら７点をあげます。</h1>

      <h1>一刀さんのお子さんの名前は何でしょう？</h1>

      <h2>ゆずるくん</h2>
      <h2>かずやくん</h2>
      <h2>かずあきくん</h2>
      <h2>なごみくん</h2>
      <h2>いづるくん</h2>
      <h2>じょうたろうくん</h2>
      <h2>たつみくん</h2>
      <h2>幻の銀次くん</h2>
      <h2>まさきくん</h2>
    </div>
  </div>
</div>

app/views/books/show.html.erb
<div class='container'>
  <div class='row'>
    <div class='col-md-3'>
      <h2>User info</h2>
      <%= render 'users/info', user: @user%>
      <h2 class="mt-3">New book</h2>
      <%= render 'form', book: @booknew %>
    </div>
    <div class='col-md-8 offset-md-1'>
  		<h2>Book detail</h2>
  		<table class='table'>
  		  <tr>
  		    <td><%= link_to user_path(@book.user) do %>
            <%= attachment_image_tag(@book.user, :profile_image, :fill, 100, 100, fallback: "no-image-icon.jpg") %><br>
            <%= @book.user.name %>
            <% end %>
          </td>
          <td><%= link_to @book.title, book_path(@book) %></td>
          <td><%= @book.body %></td>
          <% if @book.user == current_user %>
          <td><%= link_to 'Edit', edit_book_path(@book), class: "btn btn-sm btn-success edit_book_#{@book.id}" %></td>
					<td><%= link_to "Destroy",@book, method: :delete, data: {confirm: "本当に削除してもよろしいですか？"}, class: "btn-sm btn-danger destroy_book_#{@book.id}" %></td>
          <% end %>       
        </tr>
      </table>
    </div>
  </div>
</div>

app/views/boss/clear.html.erb
<div class='container px-5 px-sm-0'>
  <div class='row'>
    <div class='col-md-10'>
    <h2>ゾーマをやっつけた！</h2>
    <h2>あなたは6点を手に入れた。</h2>
  </div>
</div>

app/views/boss/takarabako.html.erb
<div class='container px-5 px-sm-0'>
  <div class='row'>
    <div class='col-md-10'>
    <h1>あなたは宝箱を開けた！</h1>
    <h1>5点をゲットした！！！！</h1>
    </div>
  </div>
</div>

app/views/boss/zoma.html.erb
<div class='container px-5 px-sm-0'>
  <div class='row'>
    <div class='col-md-10'>
    <%= image_tag 'zoma.jpeg' %>
    <div>ゾーマ「私を倒せるかな？」</div>
      <%= link_to 'マナブーメラン', danger_path, class: "btn btn-secondary btn-sm btn-block" %>
      <%= link_to 'ギガスラッシュ', clear_path, class: "btn btn-secondary btn-sm btn-block"%>
      <%= link_to 'カツマダンテ', danger_path, class: "btn btn-secondary btn-sm btn-block"%>
    </div>
  </div>
</div>

app/views/homes/about.html.erb
<div class='container'>
  <div class="row">
    <h1>何故押すなと言ったのに押したのでしょう？</h1><br>
    <h1>今なら下のボタンを押さずに、戻ってもいいですよ。</h1>
  </div>
  <div class='row'>
    <a href="/dangerbtn" class="btn-real-dent">
      <i class="fas fa-exclamation-triangle"></i>
    </a>
  </div>
</div>

app/views/homes/top.html.erb
<div class="container">
  <div class="row">
    <div class='mx-auto col-11 col-sm-10 col-lg-8 col-xl-6'>
      <h1>welcome to <i class="fas fa-beer"></i><strong>Bounenkai</strong>  !!</h1>
      <p>In  <i class="fas fa-beer"></i><strong>Bounenkai</strong>, </p>
      <p>you can share and exchange  your SAKE , inpressions , and emotions</p>
      <p> about various alcohol!</p>
      <% unless user_signed_in? %>
      <div class="btn-wrapper col-10 mx-auto">
        <div class="row">
          <%= link_to 'Log in',new_user_session_path, class: "btn btn-info btn-sm btn-block mb-3 sign_in" %>
        </div>
        <div class="row">
          <%= link_to 'Sign Up',new_user_registration_path, class: "btn btn-success btn-sm btn-block mb-3 sign_up" %>
        </div>
        <div class="row">
          <%= link_to 'Danger',danger_path, class: "btn btn-danger btn-sm btn-block sign_up" %>
        </div>
      </div>
      <% else %>
      <h1>なぜわざわざBounenkaiのタイトルをクリックした？</h1>
      <h1>貴様飲み足りていないな。</h1>
      <h1>4点とビールくれてやろう。（お酒を注文してください）</h1>
      <% end%>
    </div>
  </div>
</div>

app/views/layouts/_errors.html.erb
<% if obj.errors.any? %>
  <div id="error_explanation">
    <h3><%= pluralize(obj.errors.count, "error") %> prohibited this obj from being saved:</h3>
    <ul>
      <% obj.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_footer.html.erb
<footer>
  <div class='container mt-5'>
    <div class='row'>
      <div class='mx-auto'>
        <p>CopyRight Infratop.inc</p>
      </div>
    </div>
  </div>
</footer>

app/views/layouts/_header.html.erb
<header>
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container">
      <a class="navbar-brand" href="/"><span>Bounenkai</span></a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <ul class="navbar-nav ml-auto">
        <% if user_signed_in? %>
          <li><%= link_to ' Home',user_path(current_user),class: 'fas fa-home nav-link text-light' %></li>
          <li><%= link_to ' Users',users_path,class: 'fas fa-users nav-link text-light' %></li>
          <li><%= link_to ' Books',books_path ,class: 'fas fa-book-open nav-link text-light'%></li>
          <li><%= link_to ' logout', destroy_user_session_path, method: :delete,class: 'fas fa-sign-out-alt nav-link text-light' %></li>
        <% else %>
          <li><%= link_to ' Home',root_path,class: 'fas fa-home nav-link text-light' %></li>
          <li><%= link_to ' Osuna',home_about_path,class: 'fas fa-link nav-link text-light' %></li>
          <li><%= link_to ' sign up', new_user_registration_path,class: 'fas fa-user-plus nav-link text-light' %></li>
          <li><%= link_to ' login', new_user_session_path ,class: 'fas fa-sign-in-alt nav-link text-light'%></li>
        <% end %>
        </ul>
      </div>
    </div>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Nomikai</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.9.0/css/all.css"> <!-- 追加 -->
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
      <main>
        <a href="/notice"><p id="notice"><%= notice %></p></a>
      </main>
    <%= yield %>
    <%= render 'layouts/footer' %>

  </body>
</html>

app/views/users/_index.html.erb
<table class='table'>
  <thead>
    <tr>
      <th>image</th>
      <th>name</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% users.each do |user| %>
      <tr>
        <td><%= attachment_image_tag(user, :profile_image, :fill, 50, 50, fallback: "no-image-icon.jpg") %></td>
        <td><%= user.name %></td>
        <td><%= link_to 'Show', user_path(user), class: "user_#{user.id}" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/users/_info.html.erb
<table class='table'>
  <tr><%= attachment_image_tag(user, :profile_image, :fill, 100, 100, fallback: "no_image.jpg") %></tr>
  <tr>
	  <th>name</th>
	  <th><%= user.name %></th>
  </tr>
  <tr>
	  <th>introduction</th>
	  <th><%= user.introduction %></th>
  </tr>
</table>

<div class='row'>
  <%= link_to '',edit_user_path(user),class: "btn btn-outline-secondary btn-block fas fa-user-cog edit_user_#{user.id}" %>
</div>

app/views/users/correct.html.erb
<div class='container px-5 px-sm-0'>
  <div class='row'>
    <div class='col-md-8'>
      <h3>西河さん「大正解です！１点をプレゼントします。」</h3>
      <h3>あなたは1点を獲得した。</h3>
    </div>
  </div>
</div>

app/views/users/dangerbtn.html.erb
<div class='container px-5 px-sm-0'>
  <div class='row'>
    <div class='col-md-10'>
      <h3><%= "あなたは度胸がある。" + "#{@point + 3 + 1 - 5 + 2 - 2}点" + "を手に入れた。"%></h3>
      <h3>これからも色々挑戦していきましょう！！！</h3>
    </div>
  </div>
</div>

app/views/users/edit.html.erb
<div class='container'>
  <div class='row'>
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
    <h2>User info</h2>
    
    <%= form_with model:@user, local:true do |f| %>
      <%= render 'layouts/errors', obj: @user %>
      <div class="form-group">
        <%= f.label :name %>
        <%= f.text_field :name, class: "form-control name" %>
      </div>
     <div class="form-group">
        <%= f.label :image %>
        <%= f.attachment_field :profile_image, class: "form-control-file user_image" %>
      </div>
      <div class="form-group">
        <%= f.label :introduction %>
        <%= f.text_area :introduction, class: "form-control introduction" %>
      </div>
      <div class="form-group">
        <%= f.submit class: 'btn btn-secondary' %>
      </div>
    <% end %>
  </div>
</div>

app/views/users/index.html.erb
<div class='container px-5 px-sm-0'>
  <div class='row'>
    <div class='col-md-3'>

      <h2>User info</h2>
      <%= render 'info', user: current_user %>
      <h2 class="mt-3">New book</h2>
      <%= render 'books/form', book: @book %>
    </div>

    <div class='col-md-8 offset-md-1'>

      <h2>Users</h2>
      <% if current_user.name == "nonbe" %>
        <h1>あなたは飲兵衛さんですね！！！！</h1>
        <h1>こちらをお受け取りください。</h1>
        <h1>あなたは3点を受け取った。</h1>
      <% end %>
      <%= render 'index', users: @users %>
    </div>
  </div>
</div>

app/views/users/ougon.html.erb
<div class='container px-5 px-sm-0'>
  <div class='row'>
    <h3>Nishikawaさん「私の名前の漢字を答えてください。」</h3>
    <div class='col-md-5'>
      <%= link_to '西河さん', correct_path, class: "btn btn-success btn-sm btn-block" %>
      <%= link_to '西川さん', danger_path, class: "btn btn-primary btn-sm btn-block"%>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class='container px-5 px-sm-0'>
  <div class='row'>
    <div class='col-md-3'>
      <h2>User info</h2>
      <%= render 'info', user: @user %>
      <h2 class="mt-3">New book</h2>
      <%= render 'books/form', book: @book %>
    </div>
    <div class='col-md-8 offset-md-1'>
      <h2>Books</h2>
      <%= render 'books/index',books: @books %>
    </div>
  </div>
</div>